version: "3.8"

services:
  mongodb:
    image: mongo:7.0.15
    container_name: ekart-mongodb
    ports:
      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data-fresh:/data/db

volumes:
  mongo-data-fresh:


