server:
  port: 8085

spring:
  application:
    name: cart-service

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}

  data:
    mongodb:
      uri: mongodb://localhost:27018/ekartCartdb

  docker:
    compose:
      enable: true
      lifecycle-management: start-and-stop

jwt:
  secret: ${JWT_SECRET}
